[package]
name = "kyberlib"
version = "0.0.3"
authors = ["The kyberlib contributors <contact@kyberlib.com>"]
edition = "2021"
description = "A Robust Rust Library for CRYSTALS-Kyber Post-Quantum Cryptography."
license = "MIT OR Apache-2.0"
repository = "https://github.com/sebastienrousseau/kyberlib"
documentation = "https://docs.rs/kyberlib"
homepage = "https://kyberlib.com"
readme = "README.md"
categories = ["algorithms", "cryptography", "wasm", "no-std"]
keywords = ["kyber", "kem", "key-exchange", "kex", "post-quantum"]
rust-version = "1.71.1"
build = "build.rs"
exclude = ["/.git/*", "/.github/*", "/.gitignore", "/.vscode/*"]
include = ["/CONTRIBUTING.md", "/LICENSE-APACHE", "/LICENSE-MIT", "/build.rs", "/Cargo.toml", "/README.md", "/src/**", "/xtask/**"]

[lib]
crate-type = ["cdylib", "rlib"]
name = "kyberlib"
path = "src/lib.rs"

[dependencies]
aes = { version = "0.8.3", optional = true }
criterion = { version = "0.5.1", optional = true }
ctr = { version = "0.9.2", optional = true }
getrandom = { version = "0.2.11", optional = true }
rand ={ version = "0.8.5", optional = true }
rand_core = { version = "0.6.4",  default-features = false }
sha2 = { version = "0.10.8", optional = true , default-features = false }
wasm-bindgen = { version = "0.2.89", optional = true }

[dev-dependencies]
rand = "0.8.5"

[build-dependencies]
cc = { version = "1.0.83", optional = true }
nasm-rs = { version = "0.2.5", optional = true }

[features]
default = ["kyber768"]
no-std = []
std = []
kyber768 = []
# kyber512 = []
# kyber1024 = []
benchmarking = ["criterion"]
90s = ["sha2"]
90s-fixslice = ["90s", "aes", "ctr"]
avx2 = ["cc"]
wasm = ["wasm-bindgen"]
nasm = ["nasm-rs", "avx2"]
hazmat = []

[package.metadata.docs.rs]
all-features = true

[workspace]
members = ["xtask"]

[profile.dev]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
opt-level = 0
overflow-checks = true
panic = 'unwind'
rpath = false
strip = false

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = "s"
overflow-checks = false
panic = "abort"
rpath = false
strip = "symbols"

[profile.test]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
opt-level = 0
overflow-checks = true
rpath = false
strip = false
